events {}

http {
    upstream express_backend {
        least_conn;
        server express-api-1:4000;
        server express-api-2:4000;
        server express-api-3:4000;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://express_backend;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Connection "";
        }

        location /nginx_status {
            stub_status on;
            access_log off;
            allow all;
        }
    }
}